name: Build

on: [push, pull_request]

jobs:
  windows-x86-64:
    runs-on: windows-2022
    env:
      CXXFLAGS: -fno-asynchronous-unwind-tables
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/checkout@v3
        with:
          repository: lichess-org/intel-sde
          ssh-key: ${{ secrets.ID_RSA_INTEL_SDE }}
          ref: main
          path: intel-sde
        id: sde
        continue-on-error: true
      - run: 7z e intel-sde/sde-external-9.0.0-2021-11-07-win.tar.xz && 7z x sde-external-9.0.0-2021-11-07-win.tar && echo SDE_PATH=$(cygpath -u $env:GITHUB_WORKSPACE\sde-external-9.0.0-2021-11-07-win\sde.exe) >> $env:GITHUB_ENV
        if: steps.sde.outcome == 'success'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable-x86_64-pc-windows-gnu
          target: x86_64-pc-windows-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-gnu -vv
      - run: mv target/x86_64-pc-windows-gnu/release/fishnet.exe fishnet-x86_64-pc-windows-gnu.exe
      - uses: actions/upload-artifact@v3
        with:
          name: fishnet-x86_64-pc-windows-gnu
          path: fishnet-x86_64-pc-windows-gnu.exe
